package Views.Administradores;

import proyectoesport_moh.Controladora;
import Exceptions.*;

/**
 * @author MIGUEL
 */
public class VPanelAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form VAdministracion
     */
    public VPanelAdministracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMadministradores = new javax.swing.JMenuItem();
        jMduenios = new javax.swing.JMenuItem();
        jMjugadores = new javax.swing.JMenuItem();
        jMusuarios = new javax.swing.JMenuItem();
        jMequipos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMcalendario = new javax.swing.JMenuItem();
        jMresultados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PANEL DE ADMINISTRADORES");

        jLabel2.setText("Bienvenid@ de nuevo");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Retroceder");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");

        jMadministradores.setText("CRUD Administradores");
        jMadministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMadministradoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMadministradores);

        jMduenios.setText("CRUD Duenios");
        jMduenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdueniosActionPerformed(evt);
            }
        });
        jMenu2.add(jMduenios);

        jMjugadores.setText("CRUD Jugadores");
        jMjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMjugadoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMjugadores);

        jMusuarios.setText("CRUD Usuarios");
        jMusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMusuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMusuarios);

        jMequipos.setText("CRUD Equipos");
        jMequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMequiposActionPerformed(evt);
            }
        });
        jMenu2.add(jMequipos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gestionar");

        jMcalendario.setText("Calendarios");
        jMenu3.add(jMcalendario);

        jMresultados.setText("Resultados");
        jMenu3.add(jMresultados);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // APERTURAS DE LAS VISTAS CRUD / ADMINISTRADORES / USUARIOS / DUENOS / JUGADORES / EQUIPOS
    private void jMadministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMadministradoresActionPerformed
        // ACTION CRUD ADMINISTRADORES
        Controladora.abrirCrudAdministradores();
        Controladora.cierraMe();
    }//GEN-LAST:event_jMadministradoresActionPerformed

    private void jMjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMjugadoresActionPerformed
        // ACTION CRUD JUGADORES
        Controladora.abrirCrudJugadores();
        Controladora.cierraMe();
    }//GEN-LAST:event_jMjugadoresActionPerformed

    private void jMdueniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdueniosActionPerformed
        // ACTION CRUD DUENIOS
        Controladora.abrirCrudDuenios();
        Controladora.cierraMe();
    }//GEN-LAST:event_jMdueniosActionPerformed

    private void jMusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMusuariosActionPerformed
        // ACTION CRUD USUARIOS
        Controladora.abrirCrudUsuarios();
        Controladora.cierraMe();
    }//GEN-LAST:event_jMusuariosActionPerformed

    private void jMequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMequiposActionPerformed
        // ACTION CRUD EQUIPOS
        Controladora.abrirCrudEquipos();
        Controladora.cierraMe();
    }//GEN-LAST:event_jMequiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPanelAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPanelAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPanelAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPanelAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPanelAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMadministradores;
    private javax.swing.JMenuItem jMcalendario;
    private javax.swing.JMenuItem jMduenios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMequipos;
    private javax.swing.JMenuItem jMjugadores;
    private javax.swing.JMenuItem jMresultados;
    private javax.swing.JMenuItem jMusuarios;
    // End of variables declaration//GEN-END:variables
}
